name: Node CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Decrypt API keys
      run: ./.github/scripts/decrypt_api_keys.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.API_KEY_SAFE }}
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
        
